### ISSUE TITLE
display property name [object] [object]

### ISSUE THREAD

**Issue by matteobaldelli** [ng2-ui/auto-complete#210]
**Steps to reproduce and a minimal demo**

  - http://plnkr.co/edit/GTJy9PSMoiTnHkLVROT3?p=preview
  - click on button "Default"

**Current behavior**

  - in autocomplete have [object Object]

**Expected/desired behavior**

  - i expected value of name (Antartica)

**Comment by gundawarprasad** [comment]
use list-formatter.
Ref From:
https://www.npmjs.com/package/ng2-auto-complete

**Comment by spielma** [comment]
+1  Same problem.  Has anyone found a solution?
In the demo, @matteobaldelli seems to be using the list-formatter to no avail as well.

**Comment by allenhwkim** [comment]
When you assign an object to the value, the value formatter is not invoked to format the value to string because ng2-auto-complete does not know its value is changed or not.

http://plnkr.co/edit/u8CWDe6lKiSi61aer9Uc?p=preview

As you see in the example, please assign value of toString function separately for this case.

**Comment by spielma** [comment]
Thanks!!  It would be great if the directive used the list-formatter to create the toString() automatically, but this will get the job done.
