### ISSUE TITLE
open-on-focus is ignored on Internet Explorer

### ISSUE THREAD

**Issue by lstolowski** [ng2-ui/auto-complete#293]
It doesn't matter if option open-on-focus=false is set or not. ngui-auto-complete div still appears on Internet Explorer 11.

**Comment by kevinp1335** [comment]
It's not just Internet Explorer. It's doing this for me in Chrome as well. The @Input openOnFocus is being read as a string even though it's set to be a boolean. So, in the ngAfterViewInit function when it checks "if (this.openOnFocus)", this expression is always true because this.openOnFocus is a string of the word 'false'.

**Comment by danail-vasilev** [comment]
Hi Guys,
Yes, this issue is reproducible in Chrome as well. Is there any workaround ?

**Comment by kevinhoelscher** [comment]
I've been testing this locally and may have a workaround.  It seems to work if you use the one-way data binding syntax:

`[open-on-focus]="false" // works`
`open-on-focus="false" // doesn't work`

Note that the similar close-on-focusout *does not* seem to work using this approach.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
